config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'

  resources :users do
    collection do
      get 'notifications'
    end
  end

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :shows do
    member do
      get 'admin'
    end
  end
  resources :events do
    resources :event_members, :only  => [:create]
  end
  resources :tickets, :only => [:index, :create]
  resources :venues
  resources :followings, :only => [:index, :create, :destroy]
  resources :friendships, :only => [:index, :create, :update, :destroy]
  resources :videos, :only => [:create, :destroy]
  resources :images, :only => [:create, :destroy]
  resources :companies

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'home_page#search', :as => :search

  get 'notifications' => 'home_page#notifications'

  get 'requests' => 'friendships#requests'
  get 'followers' => 'followings#followers'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :events

  validates :name, :presence => true

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  has_many :events

  mount_uploader :image, AvatarUploader

  validates :name, :description, :presence => true

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :venue
  belongs_to :category
  belongs_to :user

  has_many :shows
  accepts_nested_attributes_for :shows, :reject_if => :all_blank, :allow_destroy => true

  has_many :event_members
  accepts_nested_attributes_for :event_members, :reject_if => :all_blank, :allow_destroy => true

  has_many :tickets, through: :shows

  validates :start_date, :end_date, :price_for_general, :name, :description, :presence => true

  before_create :end_of_day

  def start_of_day
    self.start_date.beginning_of_day
  end

  def end_of_day
    self.end_date = end_date.end_of_day
  end

end

app/models/event_member.rb
class EventMember < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :friender, :class_name => 'User'
  belongs_to :friendee, :class_name => 'User'

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, AvatarUploader

  belongs_to :imageable, polymorphic: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :event
  has_many :tickets

  validates :date, :presence => true
  before_create :within_event_run?

  def within_event_run?
    @event = Event.find(event_id)
    date >= @event.start_date && date <= @event.end_date
  end

  def available?(num_of_general)
    @event = Event.find(event_id)
    @venue = Venue.find(@event.venue_id)
    tickets_for_show = tickets.all
    tickets_for_show.sum(:num_of_general) + num_of_general <= @venue.num_of_seats
  end

  def tickets_sold
    tickets_for_show = tickets.all
    tickets_for_show.sum(:num_of_general)
  end

  def tickets_remaining
    @event = Event.find(event_id)
    @venue = Venue.find(@event.venue_id)
    @venue.num_of_seats - tickets_sold
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :show
  has_one :event, through: :show
  belongs_to :user

  validates :num_of_general, :presence => true
  before_save :check_capacity

  def cost_of_tickets
    event.price_for_general * num_of_general
  end

  def check_capacity
    show.available?(num_of_general)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader


  validates :password, length: {minimum: 6}, :on => :create
  validates :password, confirmation: true, :on => :create
  validates :password_confirmation, presence: true, :on => :create

  validates :email, uniqueness: true

  validates :first_name, :last_name, :presence => true

  has_many :tickets

  has_many :companies
  has_many :events

  has_many :venues

  has_many :event_members

  has_many :followees, :foreign_key => "follower_id", class_name: "Following"
  has_many :followers, :foreign_key => "followee_id", class_name: "Following"
  has_many :followed_users, through: :followees, source: :followee
  has_many :users_following, through: :followers, source: :follower

  has_many :friendees, :foreign_key => "friender_id", :class_name => "Friendship"
  has_many :frienders, :foreign_key => "friendee_id", :class_name => "Friendship"
  has_many :friended_users, :through => :friendees, :source => :friendee
  has_many :users_friending, :through => :frienders, :source => :friender

  has_many :notifications

  has_many :videos
  has_many :images, :as => :imageable

  def full_name
    "#{first_name} #{last_name}"
  end

  def friends
    friended_users + users_friending
  end

  def unconfirmed_friendees
    friendees.where(confirmed: false)
  end

  def arts_worker?
    arts_worker
  end

  def gravatar
    self.avatar = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.strip.downcase)}?d=mm"
  end

  def confirmed_friends
    friendees.where(confirmed: true) + frienders.where(confirmed:true)
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :num_of_seats, :address_one, :city, :province, :country, :name, :description, :presence => true

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{address_one}, #{city}, #{province}, #{country}"
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :url, presence: true, format: YT_LINK_FORMAT

  before_create do
    youtube_id = url.match(YT_LINK_FORMAT)
    self.youtube_id = youtube_id[2] if youtube_id && youtube_id[2]
  end

end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  skip_before_filter :require_login

  def index
  end

  def search
    if params[:search]
      @users = User.where("LOWER(first_name) LIKE LOWER(?) OR LOWER(last_name) LIKE LOWER(?)",
                          "%#{params[:search]}%", "%#{params[:search]}%")
      @venues = Venue.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
      @events = Event.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    end

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def notifications
    @notifications = current_user.notifications.where(:viewed => false)
    @request_notifications = @notifications.where(:notification_type => 0)
    @friend_notifications = @notifications.where(:notification_type => 1)
    @follower_notifications = @notifications.where(:notification_type => 2)

    respond_to do |f|
      f.js {}
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home_page/index.html.erb
<div class="home-page-content">
  <div class="home-page-welcome">
    <h1>Welcome to ArsUnita!</h1>
    <p>This is a site for those who work in the arts and those who enjoy the arts.</p>

    <p><%= link_to "Register", new_user_path(arts_worker: true) %> today as an arts worker to start building an online image and generate a following.</p>

    <p class="or-break">OR</p>

    <p><%= link_to "Sign up", new_user_path %> today to start discovering what artists in your area are up to. If you find someone who's work intrigues you follow them and keep up to date with their future endeavours!</p>
  </div>
  <%= form_tag user_sessions_path, :class => 'home-page-form' do %>
    <%= label_tag :email, "Email" %>
    <%= email_field_tag :email %>
    <%= label_tag :password, "Password" %>
    <%= password_field_tag :password %>
    <%= label_tag :remember, "Remember me after login" %>
    <%= check_box_tag :remember %>
    <%= button_tag "Login", :class => 'btn-login' %>
  <% end %>
</div>

app/views/home_page/notifications.js.erb
<% if @notifications.any? %>
  $("#notifications").html(<%= @notifications.count %>).show()
<% else %>
  $("#notifications").hide()
<% end %>
<% if @request_notifications.any? %>
  $("#request-notifications").html(<%= @request_notifications.count %>).show()
  <% else %>
  $("#request-notifications").hide()
<% end %>
<% if @friend_notifications.any? %>
  $("#friend-notifications").html(<%= @friend_notifications.count %>).show()
  <% else %>
  $("#friend-notifications").hide()
<% end %>
<% if @follower_notifications.any? %>
  $("#follower-notifications").html(<%= @follower_notifications.count %>).show()
  <% else %>
  $("#follower-notifications").hide()
<% end %>

app/views/home_page/search.js.erb
$('#search-results').html("<%= j(render 'layouts/search') %>");
hideIfNothing();

app/views/home_page/sidebar.html.erb
<% if current_user %>
 <sidebar>
   <%= link_to "Change Profile Picture", "#", :class => 'btn-change-avatar' %>
   <%= link_to "Friend Requests", requests_path, :class => 'btn-user btn-user-social' %>
#   <%= link_to "Friends", friendships_path, :class => 'btn-user btn-user-social' %>
#   <%= link_to "Tickets", tickets_path, :class => 'btn-user btn-user-social' %>
#   <%= link_to "Following", followings_path, :class => 'btn-user btn-user-social' %>
#   <%= link_to "Edit Profile", edit_user_path(current_user), :class => 'btn-user' %>
#   <% if current_user.arts_worker? %>
#     <%= link_to "Followers", followers_path, :class => 'btn-user btn-user-social' %>
#     <%= link_to "Create Event", new_event_path, :class => 'btn-user' %>
#     <%= link_to "Create Venue", new_venue_path, :class => 'btn-user' %>
#     <%= form_for @user do |f| %>
#       <%= f.file_field :avatar %>
#       <%= f.hidden_field :avatar_cache %>
#       <%= f.button %>
#     <% end %>
#   <% end %>
# </sidebar>
# <% end %>