config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'

  resources :users do
    collection do
      get 'notifications'
    end
  end

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :shows do
    member do
      get 'admin'
    end
  end
  resources :events do
    resources :event_members, :only  => [:create]
  end
  resources :tickets, :only => [:index, :create]
  resources :venues
  resources :followings, :only => [:index, :create, :destroy]
  resources :friendships, :only => [:index, :create, :update, :destroy]
  resources :videos, :only => [:create, :destroy]
  resources :images, :only => [:create, :destroy]
  resources :companies

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'home_page#search', :as => :search

  get 'notifications' => 'home_page#notifications'

  get 'requests' => 'friendships#requests'
  get 'followers' => 'followings#followers'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :events

  validates :name, :presence => true

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  has_many :events

  mount_uploader :image, AvatarUploader

  validates :name, :description, :presence => true

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :venue
  belongs_to :category
  belongs_to :user

  has_many :shows
  accepts_nested_attributes_for :shows, :reject_if => :all_blank, :allow_destroy => true

  has_many :event_members
  accepts_nested_attributes_for :event_members, :reject_if => :all_blank, :allow_destroy => true

  has_many :tickets, through: :shows

  validates :start_date, :end_date, :price_for_general, :name, :description, :presence => true

  before_create :end_of_day

  def start_of_day
    self.start_date.beginning_of_day
  end

  def end_of_day
    self.end_date = end_date.end_of_day
  end

end

app/models/event_member.rb
class EventMember < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :friender, :class_name => 'User'
  belongs_to :friendee, :class_name => 'User'

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, AvatarUploader

  belongs_to :imageable, polymorphic: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :event
  has_many :tickets

  validates :date, :presence => true
  before_create :within_event_run?

  def within_event_run?
    @event = Event.find(event_id)
    date >= @event.start_date && date <= @event.end_date
  end

  def available?(num_of_general)
    @event = Event.find(event_id)
    @venue = Venue.find(@event.venue_id)
    tickets_for_show = tickets.all
    tickets_for_show.sum(:num_of_general) + num_of_general <= @venue.num_of_seats
  end

  def tickets_sold
    tickets_for_show = tickets.all
    tickets_for_show.sum(:num_of_general)
  end

  def tickets_remaining
    @event = Event.find(event_id)
    @venue = Venue.find(@event.venue_id)
    @venue.num_of_seats - tickets_sold
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :show
  has_one :event, through: :show
  belongs_to :user

  validates :num_of_general, :presence => true
  before_save :check_capacity

  def cost_of_tickets
    event.price_for_general * num_of_general
  end

  def check_capacity
    show.available?(num_of_general)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader


  validates :password, length: {minimum: 6}, :on => :create
  validates :password, confirmation: true, :on => :create
  validates :password_confirmation, presence: true, :on => :create

  validates :email, uniqueness: true

  validates :first_name, :last_name, :presence => true

  has_many :tickets

  has_many :companies
  has_many :events

  has_many :venues

  has_many :event_members

  has_many :followees, :foreign_key => "follower_id", class_name: "Following"
  has_many :followers, :foreign_key => "followee_id", class_name: "Following"
  has_many :followed_users, through: :followees, source: :followee
  has_many :users_following, through: :followers, source: :follower

  has_many :friendees, :foreign_key => "friender_id", :class_name => "Friendship"
  has_many :frienders, :foreign_key => "friendee_id", :class_name => "Friendship"
  has_many :friended_users, :through => :friendees, :source => :friendee
  has_many :users_friending, :through => :frienders, :source => :friender

  has_many :notifications

  has_many :videos
  has_many :images, :as => :imageable

  def full_name
    "#{first_name} #{last_name}"
  end

  def friends
    friended_users + users_friending
  end

  def unconfirmed_friendees
    friendees.where(confirmed: false)
  end

  def arts_worker?
    arts_worker
  end

  def gravatar
    self.avatar = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.strip.downcase)}?d=mm"
  end

  def confirmed_friends
    friendees.where(confirmed: true) + frienders.where(confirmed:true)
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :num_of_seats, :address_one, :city, :province, :country, :name, :description, :presence => true

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{address_one}, #{city}, #{province}, #{country}"
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :url, presence: true, format: YT_LINK_FORMAT

  before_create do
    youtube_id = url.match(YT_LINK_FORMAT)
    self.youtube_id = youtube_id[2] if youtube_id && youtube_id[2]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login, only: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @event_members = @user.event_members
    if current_user
      if current_user.arts_worker?
        @video = current_user.videos.build
        @image = current_user.images.build
      end
    end
  end

  def new
    if params[:arts_worker] == "true"
      @artist = true
    end
      @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to user_url(@user), :notice => 'User Created'
    else
      flash.now[:alert] = 'User creation failed'
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to user_url(@user), :notice => 'User Updated' }
        format.js {}
      else
        format.html { flash.now[:alert] = 'User edit failed'; render 'edit'}
        format.js {}
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to users_url, :notice => 'User deleted'
  end

private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :profession, :description, :avatar, :arts_worker, :avatar_cache)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/users/_form.html.erb
<%= f.label :first_name, "First Name" %>
<%= f.text_field :first_name %>
<%= f.label :last_name, "Last Name" %>
<%= f.text_field :last_name %>
<%= f.label :description, "Description" %>
<%= f.text_area :description %>
<% if @artist %>
  <%= f.label :profession, "Profession" %>
  <%= f.text_field :profession %>
  <%= f.hidden_field :arts_worker, :value => true %>
<% end %>

app/views/users/_profile_image.html.erb
<% if @user.avatar_url %>
  <%= image_tag @user.avatar_url, :class => 'profile-picture' %>
<% else %>
  <%= image_tag @user.gravatar, :class => 'profile-picture' %>
<% end %>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
  <%= f.text_area :description %>
  <%= f.button %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<%= form_for @user do |f| %>
  <%= render 'form', :f => f %>
  <% if current_user.arts_worker? %>
    <%= f.label :profession, "Profession" %>
    <%= f.text_field :profession %>
  <% end %>
  <%= f.label :avatar, "Avatar" %>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :avatar_cache %>
  <%= f.button %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="users">
  <% @users.each do |user| %>
    <div class="user-card">
      <h2><%= link_to "#{user.full_name}", user_path(user) %></h2>
      <% if user.arts_worker? %>
        <p><%= user.profession %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% if @artist %>
  <h1>New Arts Worker</h1>
<% else %>
  <h1>New User</h1>
<% end %>

<%= form_for @user do |f| %>
  <%= render 'form', :f => f %>
  <%= f.label :email, "Email" %>
  <%= f.email_field :email %>
  <%= f.label :password, "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "Password Confirmation" %>
  <%= f.password_field :password_confirmation %>
  <%= f.button "Create Profile" %>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="col-left">
    <div class="profile-image">
      <%= render 'profile_image' %>
    </div>
    <% if current_user && user_profile %>
        <%= link_to "Change Avatar", '#', 'data-link' => 'add-avatar', :class => 'btn-add' %>
        <div id="add-avatar" class="add-asset">
          <h2>Change Avatar</h2>
          <div class="container">
            <%= form_for @user, :remote => true do |f| %>
              <%= f.label :avatar, "Avatar Upload" %>
              <%= f.file_field :avatar %>
              <%= f.hidden_field :avatar_cache %>
              <%= f.button %>
            <% end %>
          </div>
        </div>
      <% end %>
    <h1><%= @user.full_name %></h1>
    <% if current_user && !user_profile %>
    <div class="social-links">
      <% if @user.arts_worker? %>
        <% if !following?(@user) %>
          <%= link_to "Follow", followings_path(id: @user.id), :class => 'btn-follow' %>
        <% else %>
          <p>You are following <%= @user.full_name %></p>
        <% end %>
      <% end %>
      <% if !friends?(@user) %>
        <%= link_to "Friend", friendships_path(id: @user.id), :class => 'btn-friend' %>
      <% end %>
    </div>
  <% end %>
    <% if @user.arts_worker? %>
      <p class="profession"><%= @user.profession %></p>
    <% end %>
    <p class="description"><%= @user.description %></p>
  </div>

  <div class="col-right">
    <% if @user.arts_worker? %>

      <div class="user-events">
        <%= render @event_members %>
      </div>

      <div class="user-videos">
        <%= render 'videos/video' %>
      </div>
      <% if user_profile %>
        <%= link_to "Add Video", '#', 'data-link' => 'add-video', :class => 'btn-add' %>
        <div id="add-video" class="add-asset">
        <h2>Add Video</h2>
        <div class="container">
          <%= form_for @video, :remote => true do |f| %>
            <%= f.label :url, "Youtube Video Link" %>
            <%= f.text_field :url %>
            <%= f.button %>
          <% end %>
        </div>
      </div>
      <% end %>
      <div class="user-images">
        <%= render 'images/image' %>
      </div>
      <% if user_profile %>
        <%= link_to "Add Image", '#', 'data-link' => 'add-image', :class => 'btn-add' %>
        <div id="add-image" class="add-asset">
          <h2>Add Image</h2>
          <div class="container">
            <%= form_for @image, :remote => true do |f| %>
              <%= f.label :name, "Image Upload" %>
              <%= f.file_field :image %>
              <%= f.hidden_field :image_cache %>
              <%= f.button %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.js.erb
$('.description').on('click', function(){
  $(this).replaceWith("<%= j(render 'user_form')  %>")
});

app/views/users/update.js.erb
$('.profile-image').html("<%= j(render 'profile_image') %>");