config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'

  resources :users do
    collection do
      get 'notifications'
    end
  end

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :shows do
    member do
      get 'admin'
    end
  end
  resources :events do
    resources :event_members, :only  => [:create]
  end
  resources :tickets, :only => [:index, :create]
  resources :venues
  resources :followings, :only => [:index, :create, :destroy]
  resources :friendships, :only => [:index, :create, :update, :destroy]
  resources :videos, :only => [:create, :destroy]
  resources :images, :only => [:create, :destroy]
  resources :companies

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'home_page#search', :as => :search

  get 'notifications' => 'home_page#notifications'

  get 'requests' => 'friendships#requests'
  get 'followers' => 'followings#followers'

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :venue
  belongs_to :category
  belongs_to :user

  has_many :shows
  accepts_nested_attributes_for :shows, :reject_if => :all_blank, :allow_destroy => true

  has_many :event_members
  accepts_nested_attributes_for :event_members, :reject_if => :all_blank, :allow_destroy => true

  has_many :tickets, through: :shows

  validates :start_date, :end_date, :price_for_general, :name, :description, :presence => true

  before_create :end_of_day

  def start_of_day
    self.start_date.beginning_of_day
  end

  def end_of_day
    self.end_date = end_date.end_of_day
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :require_login, only: [:index, :show]

  def index
    @categories = Category.all
    if params[:search]
      if params[:search].to_i == @categories.length + 1
        @events = Event.all
      else
        @events = Event.where(category_id: params[:search])
      end
    elsif params[:longitude] && params[:latitude]
      @venues = Venue.near([params[:latitude], params[:longitude]], 1, units: :km)
      @events = @venues.map {|venue| venue.events }
      @events.flatten!
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @event = Event.find(params[:id])
    @shows = @event.shows
    @ticket = Ticket.new
    @event_member = EventMember.new
    @users = User.where(arts_worker: true)
    @members = @event.event_members
  end

  def new
    @companies = current_user.companies
    @event = Event.new
    @venues = Venue.all
    @users = User.where(arts_worker: true)
    @categories = Category.all
  end

  def create
    @companies = current_user.companies
    @users = User.all
    @venues = Venue.all
    @categories = Category.all
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to event_url(@event), :notice => 'Created Event'
    else
      flash.now[:alert] = 'Event did not save'
      render 'new'
    end
  end

  def edit
    @companies = current_user.companies
    @event = Event.find(params[:id])
    @venues = Venue.all
    @users = User.where(arts_worker: true)
    @categories = Category.all
  end

  def update
    @companies = current_user.companies
    @users = User.where(arts_worker: true)
    @venues = Venue.all
    @categories = Category.all
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to event_url(@event), :notice => 'Event updated'
    else
      flash.now[:alert] = 'Event did not update'
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.delete
    redirect_to events_url, :notice => 'Event deleted'
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :description, :start_date, :end_date, :price_for_general, :venue_id, :category_id, :image, :company_id,
      :shows_attributes => [:id, :date, :time, :_destroy],
    )
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.erb
<% if @events.length > 0 %>
  <% @events.each do |event| %>
    <div class="event-card">
      <%= image_tag event.image %>
      <div class="event-card-details">
        <h2><%= link_to "#{event.name}", event_path(event) %></h2>
        <p>Starts: <%= event.start_date.strftime("%b %d, %Y") %></p>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="no-results">
    <h2>No events were found in that category</h2>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :description, "Description of event" %>
  <%= f.text_area :description %>
  <%= f.label :image, "Image" %>
  <%= f.text_field :image %>
  <% if @companies %>
    <%= f.label :company_id, "Company" %>
    <%= f.collection_select(:company_id, @companies, :id, :name) %>
  <% end %>
  <%= f.label :category_id, "Category" %>
  <%= f.collection_select(:category_id, @categories, :id, :name) %>
  <%= f.label :price_for_general, "Ticket Price" %>
  <%= f.number_field :price_for_general %>
  <%= f.label :start_date, "Event Start" %>
  <%= f.date_field :start_date %>
  <%= f.label :end_date, "Event End" %>
  <%= f.date_field :end_date %>
  <%= f.label :venue_id, "Venue" %>
  <%= f.collection_select(:venue_id, @venues, :id, :name) %>
  <div id="shows">
    <%= f.fields_for :shows do |show| %>
      <%= render 'show_fields', :f => show %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add show', f, :shows %>
    </div>
  </div>
  <%= f.button %>
<% end %>

app/views/events/_show_fields.html.erb
<div class="nested-fields">
  <%= f.label :date, "Day" %>
  <%= f.date_field :date %>
  <%= f.label :time, "Time" %>
  <%= f.time_field :time %>
  <%= link_to_remove_association "Remove Show", f %>
</div>

app/views/events/edit.html.erb
<div class="container">
<h1>Edit <%= @event.name %></h1>
<%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="event-index-image"></div>
<h1>Events</h1>
<div class="location">
  <h2>Search by Location</h2>
  <button id="current-location">Find Events near me</button>
</div>
<div class="categories">
  <h2>Search by Category</h2>
  <div class="categories">
    <div class="category-search">
      <% @categories.each do |category| %>
        <%= link_to category.name, events_path, :class => 'btn-category', 'data-category' => category.id %>
      <% end %>
      <%= link_to "All", events_path, :class => 'btn-category', 'data-category' => @categories.length + 1 %>
    </div>
  </div>
</div>
<div class="index-page">
  <div class="events"></div>
</div>

app/views/events/index.js.erb
$('.events').html("<%= j(render 'events') %>");
$('.event-index-image').addClass('slide-up');
$('.index-page').show();

app/views/events/new.html.erb
<div class="container">

<h1>New Event</h1>
<%= render 'form' %>

</div>

app/views/events/show.html.erb
<div class="event">
  <div class="col-left">
    <div class="event-image">
      <%= image_tag @event.image %>
    </div>
    <div class="event-info">
      <h1><%= @event.name %></h1>
      <p><%= @event.description %></p>
      <%= link_to @event.venue.name, venue_path(@event.venue) %>
      <p>Starts: <%= @event.start_date.strftime("%b %d, %Y") %></p>
      <p>Ends: <%= @event.end_date.strftime("%b %d, %Y") %></p>
      <p>General Tickets: $<%= @event.price_for_general %></p>
    </div>
  </div>
  <div class="col-right">
    <div class="featuring">
      <%= render 'event_members/member' %>
    </div>
    <% if current_user && owner?(@event) %>
      <%= link_to "Add Member", '#', 'data-link' => 'add-member', :class => 'btn-add' %>
      <div id="add-member" class="add-asset">
        <h2>Add Member</h2>
        <div class="container">
          <%= form_for [@event, @event_member], :remote => true do |f| %>
            <%= f.label :user_id, "Member" %>
            <%= f.collection_select(:user_id, @users, :id, :full_name) %>
            <%= f.label :role, "Role" %>
            <%= f.text_field :role %>
            <%= f.label :admin, "Admin" %>
            <%= f.check_box :admin %>
            <%= f.button %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="shows">
      <h2>Shows</h2>
      <ul>
        <% @event.shows.each do |show| %>
          <li><%= link_to "#{show.date.strftime('%b %d, %Y')} @ #{show.time.strftime('%I:%M:%S %p')}", show_path(show), :class => 'show-info' %></li>
          <% if current_user && owner?(@event) %>
            <li><%= link_to "Admin", admin_show_path(show), :remote => true %></li>
          <% end %>
        <% end %>
      </ul>
      <div class="show"></div>
      <div class="admin"></div>
    </div>
  </div>

    <% if current_user && owner?(@event) %>
      <div class="links">
        <%= link_to "Edit Event", edit_event_path(@event) %>
        <%= link_to "Delete Event", event_path(@event), :method => :delete %>
      </div>
    <% end %>

</div>