config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'

  resources :users do
    collection do
      get 'notifications'
    end
  end

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :shows do
    member do
      get 'admin'
    end
  end
  resources :events do
    resources :event_members, :only  => [:create]
  end
  resources :tickets, :only => [:index, :create]
  resources :venues
  resources :followings, :only => [:index, :create, :destroy]
  resources :friendships, :only => [:index, :create, :update, :destroy]
  resources :videos, :only => [:create, :destroy]
  resources :images, :only => [:create, :destroy]
  resources :companies

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'home_page#search', :as => :search

  get 'notifications' => 'home_page#notifications'

  get 'requests' => 'friendships#requests'
  get 'followers' => 'followings#followers'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :events

  validates :name, :presence => true

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  has_many :events

  mount_uploader :image, AvatarUploader

  validates :name, :description, :presence => true

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :venue
  belongs_to :category
  belongs_to :user

  has_many :shows
  accepts_nested_attributes_for :shows, :reject_if => :all_blank, :allow_destroy => true

  has_many :event_members
  accepts_nested_attributes_for :event_members, :reject_if => :all_blank, :allow_destroy => true

  has_many :tickets, through: :shows

  validates :start_date, :end_date, :price_for_general, :name, :description, :presence => true

  before_create :end_of_day

  def start_of_day
    self.start_date.beginning_of_day
  end

  def end_of_day
    self.end_date = end_date.end_of_day
  end

end

app/models/event_member.rb
class EventMember < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :friender, :class_name => 'User'
  belongs_to :friendee, :class_name => 'User'

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, AvatarUploader

  belongs_to :imageable, polymorphic: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :event
  has_many :tickets

  validates :date, :presence => true
  before_create :within_event_run?

  def within_event_run?
    @event = Event.find(event_id)
    date >= @event.start_date && date <= @event.end_date
  end

  def available?(num_of_general)
    @event = Event.find(event_id)
    @venue = Venue.find(@event.venue_id)
    tickets_for_show = tickets.all
    tickets_for_show.sum(:num_of_general) + num_of_general <= @venue.num_of_seats
  end

  def tickets_sold
    tickets_for_show = tickets.all
    tickets_for_show.sum(:num_of_general)
  end

  def tickets_remaining
    @event = Event.find(event_id)
    @venue = Venue.find(@event.venue_id)
    @venue.num_of_seats - tickets_sold
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :show
  has_one :event, through: :show
  belongs_to :user

  validates :num_of_general, :presence => true
  before_save :check_capacity

  def cost_of_tickets
    event.price_for_general * num_of_general
  end

  def check_capacity
    show.available?(num_of_general)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader


  validates :password, length: {minimum: 6}, :on => :create
  validates :password, confirmation: true, :on => :create
  validates :password_confirmation, presence: true, :on => :create

  validates :email, uniqueness: true

  validates :first_name, :last_name, :presence => true

  has_many :tickets

  has_many :companies
  has_many :events

  has_many :venues

  has_many :event_members

  has_many :followees, :foreign_key => "follower_id", class_name: "Following"
  has_many :followers, :foreign_key => "followee_id", class_name: "Following"
  has_many :followed_users, through: :followees, source: :followee
  has_many :users_following, through: :followers, source: :follower

  has_many :friendees, :foreign_key => "friender_id", :class_name => "Friendship"
  has_many :frienders, :foreign_key => "friendee_id", :class_name => "Friendship"
  has_many :friended_users, :through => :friendees, :source => :friendee
  has_many :users_friending, :through => :frienders, :source => :friender

  has_many :notifications

  has_many :videos
  has_many :images, :as => :imageable

  def full_name
    "#{first_name} #{last_name}"
  end

  def friends
    friended_users + users_friending
  end

  def unconfirmed_friendees
    friendees.where(confirmed: false)
  end

  def arts_worker?
    arts_worker
  end

  def gravatar
    self.avatar = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.strip.downcase)}?d=mm"
  end

  def confirmed_friends
    friendees.where(confirmed: true) + frienders.where(confirmed:true)
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :num_of_seats, :address_one, :city, :province, :country, :name, :description, :presence => true

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{address_one}, #{city}, #{province}, #{country}"
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :url, presence: true, format: YT_LINK_FORMAT

  before_create do
    youtube_id = url.match(YT_LINK_FORMAT)
    self.youtube_id = youtube_id[2] if youtube_id && youtube_id[2]
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    @friendships = current_user.confirmed_friends
    @notifications = Notification.where(notification_type: 1)
    @notifications.each do |notification|
      notification.update_attributes(viewed: true)
    end

    respond_to do |format|
      format.js
    end
  end

  def requests
    @requests = current_user.frienders.where(confirmed: false)
    @notifications = Notification.where(notification_type: 0)
    @notifications.each do |notification|
      notification.update_attributes(viewed: true)
    end

    respond_to do |format|
      format.js
    end
  end

  def create
    @user = User.find(params[:id])
    @friendee = current_user.friendees.build
    @friendee.friendee_id = @user.id
    @friendee.save
    respond_to do |format|
      if @friendee.save
        @notification = @user.notifications.create(notification_type: 0)
        format.html { redirect_to user_path(@user), :notice => "User friended pending acceptance" }
        format.js
      else
        format.html { render 'show' }
        format.js
      end
    end

  end

  def update
    @friendship = Friendship.find(params[:id])
    @user = @friendship.friender
    @friendship.confirmed = true
    respond_to do |format|
      if @friendship.save
        @notification = @user.notifications.create(notification_type: 1)
        format.html { redirect_to user_path(@user) }
        format.js
      else
        format.html { render 'show' }
        format.js
      end
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    respond_to do |format|
      if @friendship.delete
        format.html
        format.js
      else
        format.html
        format.js
      end
    end
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/friendships/_friendship.html.erb
<div id="friends" class="container-lrg">
  <h2>Friends</h2>
  <div class="container">
    <% @friendships.each do |friendship| %>
      <% if friendship.friender == current_user %>
        <% friend = friendship.friendee %>
      <% else %>
        <% friend = friendship.friender %>
      <% end %>
      <div class="user-friend">
        <% if friend.avatar_url %>
          <%= image_tag "#{friend.avatar_url(:medium)}", :class => 'friend-image' %>
        <% else %>
          <%= image_tag "#{friend.gravatar}", :class => 'friend-image' %>
        <% end %>
        <%= link_to "#{friend.full_name}", user_path(friend), :class => 'user-link' %>
      </div>
    <% end %>
  </div>
</div>

app/views/friendships/_request.html.erb
<div id="requests" class="container-lrg">
  <h2>Requests</h2>
  <div class="container">
    <% @requests.each do |request| %>
      <% friender = request.friender %>
      <div class="user-friend">
      <% if friender.avatar_url %>
          <%= image_tag "#{friender.avatar_url(:medium)}", :class => 'friend-image' %>
        <% else %>
          <%= image_tag "#{friender.gravatar}", :class => 'friend-image' %>
        <% end %>
        <p><%= link_to "#{friender.full_name}", user_path(friender), :class => 'user-link' %></p>
        <div class="request-btns">
          <%= link_to friendship_path(request), :class => 'confirm' do %>
            &check;
          <% end %>
          <%= link_to friendship_path(request), :class => 'reject' do %>
            &#65794;
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/friendships/_unconfirmed_friendee.html.erb
<% friendee = friendship.friendee %>
<div class="container-sm">
  <%= link_to "#{friendee.full_name}", user_path(friendee), :class => 'user-link' %>
</div>

app/views/friendships/create.js.erb
$('#friends').first('container').contents().replaceWith("<%= j(render partial: 'friendships/friendship', collection: @friendships) %>");

app/views/friendships/index.js.erb
$('.lightbox').append("<%= j(render 'friendship') %>");
$('.user-link').on('click', function(){
  $('.lightbox').remove();
});
$('.lightbox').on('click', function(){
  $(this).remove();
});

app/views/friendships/requests.js.erb
$('.lightbox').append("<%= j(render 'request') %>");
$('.user-link').on('click', function(){
  $('.lightbox').remove();
});
$('.lightbox').on('click', function(){
  $(this).remove();
});